### ISSUE TITLE
[core] Initial RouterStateTree work

### ISSUE THREAD

**Issue by jaysoo** [mobx-little-router/mobx-little-router#2]
## TODO

- [x] Router state should initialize with default location.

- [x] Paths with `/` in them should build out multiple nodes so they can be matched with a path properly.

- [x] Support scheduling dynamic children if `loadChildren` is present in `RouteNode`'s `data` property.

- [x] There should be an optional `onLoadChildren` function on `data` that can transform the loaded module to `Config[]`. This allows us module exports to contain routing-agnostic data, and perform setup (e.g. DI, update reducers, etc.), and we just need to transform it into our expected type.

- [x] Make sure `createRouteNode` factory maps `loadChildren` from `Config` to the `data` property.
